# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwift MVVM Currency' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxSwift MVVM Currency
    pod 'RxSwift'  ,'~>4.1.2'
    pod 'RxCocoa'  ,'~>4.1.2'
    pod 'RxAlamofire' ,'~>4.2.0'
end
